name: one_rep_max_calc
description: 1 Rep Max Calculator is an app that lets you calculate your 1RM, and find out how much you can lift.

publish_to: 'none' 

version: 4.2.1+8

environment:
  sdk: '^3.2.0' # Welcome to Dart 3. Do not go back.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_launcher_icons: ^0.14.4
  in_app_update: ^4.2.3
  wakelock_plus: ^1.2.8 
  in_app_review: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 


flutter:
  uses-material-design: true