name: one_rep_max_calc
description: 1 Rep Max Calculator is an app that lets you calculate your 1RM, and find out how much you can lift.

publish_to: 'none' 

version: 4.1.0+6

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '3.10.1'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  flutter_launcher_icons: ^0.13.1
  in_app_update: ^4.0.1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true